# Tensorflow

> AI: the effort to automate intellectual tasks normally performed by humans.
- A.I. can be simple or complex. Tic-Tac-To, Chess or PacMan is consider A.I.
- Actual advance of A.I., like Machine Learning (ML), and Neural Networks (NN), are more complex. NN is also called deep learning.
> ML: Rather then giving the program the rules, an algorithm finds the rules for us.
- (NN part of ML) part of AI
> NN: a for of ML that uses a layered representation of data.
- DATA is the most important part of ML and AI (NN as well). Features and Labels.
> Features: input information or predictors.    
> Labels: output information or ... (what we are trying to look for or predict)
- When we do AI (ML, NN) we need data, tons of diff data, tons of diff examples.
- We train de model (AI) using training data (we have all the features and all the labels).
- When we are going to test or use the model we only pass our features.
> NEXT.. different Types of ML ¿?

## Tensors
Tensors are multi-dimensional arrays with a uniform type (called a dtype). You can see all supported dtypes at tf.dtypes.DType.    
If you're familiar with NumPy, tensors are (kind of) like np.arrays.    
All tensors are immutable like Python numbers and strings: you can never update the contents of a tensor, only create a new one.    


In [1]:
import tensorflow as tf
tf.__version__

'2.12.0'

In [2]:
string = tf.Variable('this is a string', tf.string)
number = tf.Variable(747, tf.int16)
floating = tf.Variable(3.1416, tf.float64)

string.shape, number, floating.shape

(TensorShape([]),
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=747>,
 TensorShape([]))

### Rank/Degree of Tensors
The number of dimensions involved in the tensor. Above tensors rank=0 , scalars...

In [3]:
rank1_tf = tf.Variable(['trin1', 'trin2'], tf.string)
rank2_tf = tf.Variable([[1, 2], [3, 4]], tf.int8)

rank1_tf.shape, rank2_tf.shape, rank1_tf, rank2_tf

(TensorShape([2]),
 TensorShape([2, 2]),
 <tf.Variable 'Variable:0' shape=(2,) dtype=string, numpy=array([b'trin1', b'trin2'], dtype=object)>,
 <tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
 array([[1, 2],
        [3, 4]])>)

In [4]:
tf.rank(rank1_tf), tf.rank(rank2_tf)

(<tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2>)

### Shape & reshape

In [5]:
t1_123 = tf.ones([1, 2, 3])     # [1, 2, 3] -> shape
t1_22 = tf.Variable([[1, 1], [1, 1]], tf.float32)
t5_123 = tf.Variable([[[5, 5, 5], [5, 5, 5]]])
t0_22 = tf.zeros([2, 2])

t1_123, t1_22, t5_123, t0_22

(<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
 array([[[1., 1., 1.],
         [1., 1., 1.]]], dtype=float32)>,
 <tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
 array([[1, 1],
        [1, 1]])>,
 <tf.Variable 'Variable:0' shape=(1, 2, 3) dtype=int32, numpy=
 array([[[5, 5, 5],
         [5, 5, 5]]])>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[0., 0.],
        [0., 0.]], dtype=float32)>)

In [6]:
t1_231 = tf.reshape(t1_123, [2, 3, 1])
t1_3_ = tf.reshape(t1_123, [3, -1])
t1_3b = tf.reshape(t1_231, [3, -1])

t1_231, t1_3_, t1_3b

(<tf.Tensor: shape=(2, 3, 1), dtype=float32, numpy=
 array([[[1.],
         [1.],
         [1.]],
 
        [[1.],
         [1.],
         [1.]]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.],
        [1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.],
        [1., 1.]], dtype=float32)>)

### Types of Tensors
- Variable: the only mutable
- Constant:
- Placeholder
- SparseTensor:

### Evaluation Tensosrs -> geting its value.
Tensors represents a partially complete computation -> we need to run whats call a session.
> tf.Session are gon in Tensor

In [7]:
# tf.compat.v1.disable_eager_execution()
# with tf.compat.v1.Session() as sess:
#     print(t1_123.eval())

In [8]:
# with tf.compat.v1.Session() as sess:
#     print(sess.run(t1_123))

### Reshape exercises with:
tf.zeros([5, 5, 5, 5]) - 5, 25, 125, 625